-- =============================================================================
-- 017_security_alerts.sql
-- Persistence for security alerts generated by backend rules.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.security_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type TEXT NOT NULL,
  severity TEXT NOT NULL,
  path TEXT,
  ip_address TEXT,
  details JSONB DEFAULT '{}'::jsonb,
  channel TEXT NOT NULL DEFAULT 'webhook',
  delivered BOOLEAN NOT NULL DEFAULT false,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_security_alerts_created_at
  ON public.security_alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_alerts_delivered
  ON public.security_alerts(delivered);
CREATE INDEX IF NOT EXISTS idx_security_alerts_severity
  ON public.security_alerts(severity);

ALTER TABLE public.security_alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view security alerts" ON public.security_alerts;
CREATE POLICY "Admins can view security alerts" ON public.security_alerts
  FOR SELECT USING (
    auth.uid() IN (SELECT id FROM public.admin_profiles)
  );

DROP POLICY IF EXISTS "No direct security alerts insert" ON public.security_alerts;
CREATE POLICY "No direct security alerts insert" ON public.security_alerts
  FOR INSERT WITH CHECK (false);
